Repository onboardingrooftop/sample, pull requests merged in 2019-07, with the labels that each got.

#2 Agregado el nuevo footer #1
  documento.txt
Labels: ready-for-deploy

#5 Branch #1111
  .cambios2
Labels: ready-for-review

#19 Agregado sample-lanzetti#9.js
  sample-lanzetti#9.js
Labels: ready-for-deploy

#21 Agregado sample.js #22
  sample#emiliano_buscarol.js
Labels: priorty-high
